(
    WEIGHT_ADD, HIPS_ADD, THIGH_ADD, WAIST_ADD, CHEST_ADD, BICEPS_ADD,
    EDIT_MENU, WEIGHT_EDIT, HIPS_EDIT, THIGH_EDIT, WAIST_EDIT, CHEST_EDIT, BICEPS_EDIT,
    PROGRESS_MENU, PROGRESS_PARAM, PROGRESS_OVERALL, DELETE_CONFIRM
) = range(17)
